MikeFrames:
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "MikeFrames"
  ours: true

MikeFramesPatched: 
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/mike_frames_patched_precomputed
  label_types: [onehot]
  type: video
  training_project: "MikeFramesPatched"
  preprocessed: false
  num_frames: 4
  ours: true

MikeSlidingWindow: 
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "MikeSlidingWindow"
  ours: true


AbbyFrames:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "AbbyFrames"
  ours: true

AbbySlidingWindow:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "AbbySlidingWindow"
  ours: true

AbbySlidingWindowPrecomputed:
  path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true
  training_project: "AbbySlidingWindow"
  ours: true

UCF101:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/UCF101_precomputed
  label_types: [categorical, onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "UCF101"
  ours: false
  
Caltech101: 
  path: /share/j_sun/jth264/Caltech101
  precomputed_path: /share/j_sun/jth264/Caltech101_precomputed
  label_types: [categorical, onehot]
  type: image
  preprocessed: false
  training_project: "Caltech101"
  ours: false

MikeFramesPrecomputed: 
  path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: true
  training_project: "MikeFrames"
  ours: true

MikeSlidingWindowPrecomputed:
  path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true
  training_project: "MikeSlidingWindow"
  ours: true