MikeFrames:
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "MikeFrames"

MikeFramesPatched: 
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/mike_frames_patched_precomputed
  label_types: [onehot]
  type: video
  training_project: "MikeFramesPatched"
  preprocessed: false
  num_frames: 4


MikeSlidingWindow: 
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "MikeSlidingWindow"


AbbyFrames:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "AbbyFrames"

AbbySlidingWindow:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "AbbySlidingWindow"

AbbySlidingWindowPrecomputed:
  path: /share/j_sun/jth264/abby_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true
  training_project: "AbbySlidingWindow"

UCF101:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/UCF101_precomputed
  label_types: [categorical, onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "UCF101"
  
Caltech101: 
  path: /share/j_sun/jth264/Caltech101
  precomputed_path: /share/j_sun/jth264/Caltech101_precomputed
  label_types: [categorical, onehot]
  type: image
  preprocessed: false
  training_project: "Caltech101"

MikeFramesPrecomputed: 
  path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: true
  training_project: "MikeFrames"

MikeSlidingWindowPrecomputed:
  path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true
  training_project: "MikeSlidingWindow"