HeinFishBehavior:
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: false

HeinFishBehaviorSlidingWindow: 
  path: /share/j_sun/jth264/bites_frame_annotation_splitted
  precomputed_path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false

UCF101:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/UCF101_precomputed
  label_types: [categorical, onehot]
  type: video
  num_frames: 16
  preprocessed: false
  
Caltech101: 
  path: /share/j_sun/jth264/Caltech101
  precomputed_path: /share/j_sun/jth264/Caltech101_precomputed
  label_types: [categorical, onehot]
  type: image
  preprocessed: false

HeinFishBehaviorPrecomputed: 
  path: /share/j_sun/jth264/bites_frame_annotation_precomputed
  label_types: [onehot]
  type: image
  preprocessed: true

HeinFishBehaviorSlidingWindowPrecomputed:
  path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true