MikeFrames:
  path: /share/j_sun/jth264/mike
  precomputed_path: /share/j_sun/jth264/precomputed/mike_frames
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "MikeFrames"
  ours: true


MikeFramesPatched: 
  path: /share/j_sun/jth264/mike
  precomputed_path: /share/j_sun/jth264/precomputed/mike_frames_patched_v3
  label_types: [onehot]
  type: video
  training_project: "MikeFramesPatched"
  preprocessed: false
  num_frames: 4
  ours: true

MikeFramesPatchedPrecomputed:
  path: /share/j_sun/jth264/precomputed/mike_frames_patched_v3
  label_types: [onehot]
  type: video
  training_project: "MikeFramesPatched"
  preprocessed: false
  num_frames: 4
  ours: true
  

MikeSlidingWindow: 
  path: /share/j_sun/jth264/mike
  precomputed_path: /share/j_sun/jth264/precomputed/mike_sliding_window
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "MikeSlidingWindow"
  ours: true

AbbyFrames:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/precomputed/abby_frames 
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "AbbyFrames"
  ours: true

AbbySlidingWindow:
  path: /share/j_sun/jth264/abby
  precomputed_path: /share/j_sun/jth264/precomputed/abby_sliding_window
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "AbbySlidingWindow"
  ours: true

AbbyFramesPrecomputed:
  path: /share/j_sun/jth264/precomputed/abby_frames
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "AbbyFrames"
  ours: true


AbbySlidingWindowPrecomputed:
  path: /share/j_sun/jth264/precomputed/abby_sliding_window
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "AbbySlidingWindow"
  ours: true

UCF101:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/UCF101_precomputed
  label_types: [categorical, onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "UCF101"
  ours: false

UCF101Frames:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/precomputed/UCF101_frames
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "UCF101Frames"
  ours: false

UCF101FramesPatched:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/precomputed/UCF101_frames_patched
  label_types: [onehot]
  type: video
  training_project: "UCF101FramesPatched"
  preprocessed: false
  num_frames: 4
  ours: false


UCF101SlidingWindow:
  path: /share/j_sun/jth264/UCF101_subset
  precomputed_path: /share/j_sun/jth264/precomputed/UCF101_sliding_window
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "UCF101SlidingWindow"
  ours: false

UCF101FramesPrecomputed:
  path: /share/j_sun/jth264/precomputed/UCF101_frames
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "UCF101Frames"
  ours: false

UCF101FramesPatchedPrecomputed:
  path: /share/j_sun/jth264/precomputed/UCF101_frames_patched
  label_types: [onehot]
  type: video
  training_project: "UCF101FramesPatched"
  preprocessed: false
  num_frames: 4
  ours: false

UCF101SlidingWindowPrecomputed:
  path: /share/j_sun/jth264/precomputed/UCF101_sliding_window
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: false
  training_project: "UCF101SlidingWindow"
  ours: false

  
Caltech101: 
  path: /share/j_sun/jth264/Caltech101
  precomputed_path: /share/j_sun/jth264/Caltech101_precomputed
  label_types: [categorical, onehot]
  type: image
  preprocessed: false
  training_project: "Caltech101"
  ours: false

MikeFramesPrecomputed: 
  path: /share/j_sun/jth264/precomputed/mike_frames
  label_types: [onehot]
  type: image
  preprocessed: false
  training_project: "MikeFrames"
  ours: true

MikeSlidingWindowPrecomputed:
  path: /share/j_sun/jth264/bites_frame_annotation_clips_precomputed
  label_types: [onehot]
  type: video
  num_frames: 16
  preprocessed: true
  training_project: "MikeSlidingWindow"
  ours: true