mike: 
  path: '/share/j_sun/jth264/mikev2'
  precomputed_path: '/share/j_sun/jth264/precomputed/mike'
  sliding_styles: [
    'sliding_window',
    'frames',
    'frames_w_temp',
    'sliding_window_w_temp',
    'sliding_window_w_stride',
    'patched'
  ]

abby: 
  path: '/share/j_sun/jth264/abby'
  precomputed_path: '/share/j_sun/jth264/precomputed/abby'
  sliding_styles: [
    'frames',
    'frames_w_temp',
    'sliding_window',
    'sliding_window_w_temp',
    'sliding_window_w_stride',
  ]