frames: test_frames
frames_w_temp: test_frames
sliding_window: test_sliding_window
sliding_window_w_temp: test_sliding_window
sliding_window_w_stride: test_sliding_window
fix_patched_224: test_fix_patched_512
fix_patched_512: test_fix_patched_512