videomae: 
  input_ndim: 4 #time, channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'sliding_window', 
    'sliding_window_w_temp',
    'sliding_window_w_stride',
    'test_sliding_window'
  ]
  
clip: 
  input_ndim: 3 #channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'frames', 
    'frames_w_temp',
  ]

dino: 
  input_ndim: 3 #channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'frames', 
    'frames_w_temp',
    'fix_patched_224', 
    'fix_patched_512',
    'test_frames', 
    'test_fix_patched_512'
  ]

dino_large: 
  input_ndim: 3 #channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'frames', 
    'frames_w_temp',
    'fix_patched_224',
    'fix_patched_512',
    'test_frames',
    'test_fix_patched_512'
  ]

swinv2: 
  input_ndim: 3 #channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'frames', 
    'frames_w_temp',
  ]
  
timesformer: 
  input_ndim: 4 #time, channel, height, width
  output_ndim: 2 #ntoken, embed_dim
  sliding_styles: [
    'sliding_window', 
    'sliding_window_w_temp',
    'sliding_window_w_stride',
  ]