frames: 
  window_size: 1 
  tolerance_region: 0 
  samples_per_window: 1 
  step_size: 1
  is_image_dataset: True 
  shuffle:  False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100

frames_w_temp: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  is_image_dataset: True 
  shuffle:  False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 100

sliding_window: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 16
  is_image_dataset: False 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1 
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100


sliding_window_w_temp: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 16
  is_image_dataset: False 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 1
  MAX_BUFFER_SIZE: 100

sliding_window_w_stride: 
  window_size: 16 
  tolerance_region: 7
  samples_per_window: 16 
  step_size: 32
  is_image_dataset: False 
  shuffle: False
  patch_type: "relative"
  patch_h: 1
  patch_w: 1
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100

fix_patched_224: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  is_image_dataset: False 
  shuffle:  False
  patch_type: "absolute"
  patch_h: 224
  patch_w: 224
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100

fix_patched_518: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  is_image_dataset: False 
  shuffle:  False
  patch_type: "absolute"
  patch_h: 518
  patch_w: 518
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100

patched: 
  window_size: 1 
  tolerance_region: 0
  samples_per_window: 1 
  step_size: 1
  is_image_dataset: False 
  shuffle:  False
  patch_grid_dim: 2
  temporal_sample_interval: 2
  MAX_BUFFER_SIZE: 100